/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AlertSeverity = IDL.Variant({
  'warning' : IDL.Null,
  'info' : IDL.Null,
  'critical' : IDL.Null,
});
export const Alert = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'active' : IDL.Bool,
  'routeId' : IDL.Opt(IDL.Text),
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'severity' : AlertSeverity,
});
export const BusStatus = IDL.Variant({
  'delayed' : IDL.Null,
  'active' : IDL.Null,
  'outOfService' : IDL.Null,
});
export const Bus = IDL.Record({
  'id' : IDL.Text,
  'status' : BusStatus,
  'name' : IDL.Text,
  'routeId' : IDL.Text,
  'driverName' : IDL.Text,
});
export const Route = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'color' : IDL.Text,
  'description' : IDL.Text,
});
export const Stop = IDL.Record({
  'id' : IDL.Text,
  'latitude' : IDL.Float64,
  'name' : IDL.Text,
  'routeId' : IDL.Text,
  'longitude' : IDL.Float64,
  'sequence' : IDL.Nat,
});
export const BusLocation = IDL.Record({
  'latitude' : IDL.Float64,
  'heading' : IDL.Float64,
  'speed' : IDL.Float64,
  'longitude' : IDL.Float64,
  'timestamp' : IDL.Int,
  'busId' : IDL.Text,
});
export const BusWithLocation = IDL.Record({
  'bus' : Bus,
  'location' : BusLocation,
});
export const ETAResult = IDL.Record({
  'nextBusId' : IDL.Text,
  'routeId' : IDL.Text,
  'stopName' : IDL.Text,
  'nextBusName' : IDL.Text,
  'estimatedMinutes' : IDL.Float64,
});

export const idlService = IDL.Service({
  'addAlert' : IDL.Func([Alert], [], []),
  'addBus' : IDL.Func([Bus], [], []),
  'addRoute' : IDL.Func([Route], [], []),
  'addStop' : IDL.Func([Stop], [], []),
  'getAlerts' : IDL.Func([], [IDL.Vec(Alert)], ['query']),
  'getBusLocation' : IDL.Func([IDL.Text], [IDL.Opt(BusLocation)], ['query']),
  'getBusLocations' : IDL.Func([], [IDL.Vec(BusWithLocation)], ['query']),
  'getBuses' : IDL.Func([], [IDL.Vec(Bus)], ['query']),
  'getETA' : IDL.Func([IDL.Text], [ETAResult], ['query']),
  'getRoutes' : IDL.Func([], [IDL.Vec(Route)], ['query']),
  'getStopsForRoute' : IDL.Func([IDL.Text], [IDL.Vec(Stop)], ['query']),
  'removeAlert' : IDL.Func([IDL.Text], [], []),
  'removeBus' : IDL.Func([IDL.Text], [], []),
  'removeRoute' : IDL.Func([IDL.Text], [], []),
  'removeStop' : IDL.Func([IDL.Text], [], []),
  'seedSampleData' : IDL.Func([], [], []),
  'updateBusLocation' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Float64, IDL.Float64, IDL.Float64],
      [],
      [],
    ),
  'updateBusStatus' : IDL.Func([IDL.Text, BusStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AlertSeverity = IDL.Variant({
    'warning' : IDL.Null,
    'info' : IDL.Null,
    'critical' : IDL.Null,
  });
  const Alert = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'active' : IDL.Bool,
    'routeId' : IDL.Opt(IDL.Text),
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'severity' : AlertSeverity,
  });
  const BusStatus = IDL.Variant({
    'delayed' : IDL.Null,
    'active' : IDL.Null,
    'outOfService' : IDL.Null,
  });
  const Bus = IDL.Record({
    'id' : IDL.Text,
    'status' : BusStatus,
    'name' : IDL.Text,
    'routeId' : IDL.Text,
    'driverName' : IDL.Text,
  });
  const Route = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'color' : IDL.Text,
    'description' : IDL.Text,
  });
  const Stop = IDL.Record({
    'id' : IDL.Text,
    'latitude' : IDL.Float64,
    'name' : IDL.Text,
    'routeId' : IDL.Text,
    'longitude' : IDL.Float64,
    'sequence' : IDL.Nat,
  });
  const BusLocation = IDL.Record({
    'latitude' : IDL.Float64,
    'heading' : IDL.Float64,
    'speed' : IDL.Float64,
    'longitude' : IDL.Float64,
    'timestamp' : IDL.Int,
    'busId' : IDL.Text,
  });
  const BusWithLocation = IDL.Record({ 'bus' : Bus, 'location' : BusLocation });
  const ETAResult = IDL.Record({
    'nextBusId' : IDL.Text,
    'routeId' : IDL.Text,
    'stopName' : IDL.Text,
    'nextBusName' : IDL.Text,
    'estimatedMinutes' : IDL.Float64,
  });
  
  return IDL.Service({
    'addAlert' : IDL.Func([Alert], [], []),
    'addBus' : IDL.Func([Bus], [], []),
    'addRoute' : IDL.Func([Route], [], []),
    'addStop' : IDL.Func([Stop], [], []),
    'getAlerts' : IDL.Func([], [IDL.Vec(Alert)], ['query']),
    'getBusLocation' : IDL.Func([IDL.Text], [IDL.Opt(BusLocation)], ['query']),
    'getBusLocations' : IDL.Func([], [IDL.Vec(BusWithLocation)], ['query']),
    'getBuses' : IDL.Func([], [IDL.Vec(Bus)], ['query']),
    'getETA' : IDL.Func([IDL.Text], [ETAResult], ['query']),
    'getRoutes' : IDL.Func([], [IDL.Vec(Route)], ['query']),
    'getStopsForRoute' : IDL.Func([IDL.Text], [IDL.Vec(Stop)], ['query']),
    'removeAlert' : IDL.Func([IDL.Text], [], []),
    'removeBus' : IDL.Func([IDL.Text], [], []),
    'removeRoute' : IDL.Func([IDL.Text], [], []),
    'removeStop' : IDL.Func([IDL.Text], [], []),
    'seedSampleData' : IDL.Func([], [], []),
    'updateBusLocation' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Float64, IDL.Float64, IDL.Float64],
        [],
        [],
      ),
    'updateBusStatus' : IDL.Func([IDL.Text, BusStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };