/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Alert {
  'id' : string,
  'title' : string,
  'active' : boolean,
  'routeId' : [] | [string],
  'message' : string,
  'timestamp' : bigint,
  'severity' : AlertSeverity,
}
export type AlertSeverity = { 'warning' : null } |
  { 'info' : null } |
  { 'critical' : null };
export interface Bus {
  'id' : string,
  'status' : BusStatus,
  'name' : string,
  'routeId' : string,
  'driverName' : string,
}
export interface BusLocation {
  'latitude' : number,
  'heading' : number,
  'speed' : number,
  'longitude' : number,
  'timestamp' : bigint,
  'busId' : string,
}
export type BusStatus = { 'delayed' : null } |
  { 'active' : null } |
  { 'outOfService' : null };
export interface BusWithLocation { 'bus' : Bus, 'location' : BusLocation }
export interface ETAResult {
  'nextBusId' : string,
  'routeId' : string,
  'stopName' : string,
  'nextBusName' : string,
  'estimatedMinutes' : number,
}
export interface Route {
  'id' : string,
  'name' : string,
  'color' : string,
  'description' : string,
}
export interface Stop {
  'id' : string,
  'latitude' : number,
  'name' : string,
  'routeId' : string,
  'longitude' : number,
  'sequence' : bigint,
}
export interface _SERVICE {
  'addAlert' : ActorMethod<[Alert], undefined>,
  'addBus' : ActorMethod<[Bus], undefined>,
  'addRoute' : ActorMethod<[Route], undefined>,
  'addStop' : ActorMethod<[Stop], undefined>,
  'getAlerts' : ActorMethod<[], Array<Alert>>,
  'getBusLocation' : ActorMethod<[string], [] | [BusLocation]>,
  'getBusLocations' : ActorMethod<[], Array<BusWithLocation>>,
  'getBuses' : ActorMethod<[], Array<Bus>>,
  'getETA' : ActorMethod<[string], ETAResult>,
  'getRoutes' : ActorMethod<[], Array<Route>>,
  'getStopsForRoute' : ActorMethod<[string], Array<Stop>>,
  'removeAlert' : ActorMethod<[string], undefined>,
  'removeBus' : ActorMethod<[string], undefined>,
  'removeRoute' : ActorMethod<[string], undefined>,
  'removeStop' : ActorMethod<[string], undefined>,
  'seedSampleData' : ActorMethod<[], undefined>,
  'updateBusLocation' : ActorMethod<
    [string, number, number, number, number],
    undefined
  >,
  'updateBusStatus' : ActorMethod<[string, BusStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];