/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ETAResult {
    nextBusId: string;
    routeId: string;
    stopName: string;
    nextBusName: string;
    estimatedMinutes: number;
}
export interface Stop {
    id: string;
    latitude: number;
    name: string;
    routeId: string;
    longitude: number;
    sequence: bigint;
}
export interface Bus {
    id: string;
    status: BusStatus;
    name: string;
    routeId: string;
    driverName: string;
}
export interface BusWithLocation {
    bus: Bus;
    location: BusLocation;
}
export interface BusLocation {
    latitude: number;
    heading: number;
    speed: number;
    longitude: number;
    timestamp: bigint;
    busId: string;
}
export interface Alert {
    id: string;
    title: string;
    active: boolean;
    routeId?: string;
    message: string;
    timestamp: bigint;
    severity: AlertSeverity;
}
export interface Route {
    id: string;
    name: string;
    color: string;
    description: string;
}
export enum AlertSeverity {
    warning = "warning",
    info = "info",
    critical = "critical"
}
export enum BusStatus {
    delayed = "delayed",
    active = "active",
    outOfService = "outOfService"
}
export interface backendInterface {
    addAlert(alert: Alert): Promise<void>;
    addBus(bus: Bus): Promise<void>;
    addRoute(route: Route): Promise<void>;
    addStop(stop: Stop): Promise<void>;
    getAlerts(): Promise<Array<Alert>>;
    getBusLocation(busId: string): Promise<BusLocation | null>;
    getBusLocations(): Promise<Array<BusWithLocation>>;
    getBuses(): Promise<Array<Bus>>;
    getETA(stopId: string): Promise<ETAResult>;
    getRoutes(): Promise<Array<Route>>;
    getStopsForRoute(routeId: string): Promise<Array<Stop>>;
    removeAlert(alertId: string): Promise<void>;
    removeBus(busId: string): Promise<void>;
    removeRoute(routeId: string): Promise<void>;
    removeStop(stopId: string): Promise<void>;
    seedSampleData(): Promise<void>;
    updateBusLocation(busId: string, lat: number, lng: number, speed: number, heading: number): Promise<void>;
    updateBusStatus(busId: string, status: BusStatus): Promise<void>;
}
import type { Alert as _Alert, AlertSeverity as _AlertSeverity, Bus as _Bus, BusLocation as _BusLocation, BusStatus as _BusStatus, BusWithLocation as _BusWithLocation } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addAlert(arg0: Alert): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addAlert(to_candid_Alert_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAlert(to_candid_Alert_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addBus(arg0: Bus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addBus(to_candid_Bus_n5(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBus(to_candid_Bus_n5(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addRoute(arg0: Route): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addRoute(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addRoute(arg0);
            return result;
        }
    }
    async addStop(arg0: Stop): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addStop(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addStop(arg0);
            return result;
        }
    }
    async getAlerts(): Promise<Array<Alert>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAlerts();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAlerts();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBusLocation(arg0: string): Promise<BusLocation | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBusLocation(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBusLocation(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBusLocations(): Promise<Array<BusWithLocation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBusLocations();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBusLocations();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBuses(): Promise<Array<Bus>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBuses();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBuses();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getETA(arg0: string): Promise<ETAResult> {
        if (this.processError) {
            try {
                const result = await this.actor.getETA(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getETA(arg0);
            return result;
        }
    }
    async getRoutes(): Promise<Array<Route>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRoutes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRoutes();
            return result;
        }
    }
    async getStopsForRoute(arg0: string): Promise<Array<Stop>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStopsForRoute(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStopsForRoute(arg0);
            return result;
        }
    }
    async removeAlert(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeAlert(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeAlert(arg0);
            return result;
        }
    }
    async removeBus(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeBus(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeBus(arg0);
            return result;
        }
    }
    async removeRoute(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeRoute(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeRoute(arg0);
            return result;
        }
    }
    async removeStop(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeStop(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeStop(arg0);
            return result;
        }
    }
    async seedSampleData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seedSampleData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedSampleData();
            return result;
        }
    }
    async updateBusLocation(arg0: string, arg1: number, arg2: number, arg3: number, arg4: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBusLocation(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBusLocation(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async updateBusStatus(arg0: string, arg1: BusStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBusStatus(arg0, to_candid_BusStatus_n7(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBusStatus(arg0, to_candid_BusStatus_n7(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_AlertSeverity_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AlertSeverity): AlertSeverity {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Alert_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Alert): Alert {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_BusStatus_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BusStatus): BusStatus {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_BusWithLocation_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BusWithLocation): BusWithLocation {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_Bus_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Bus): Bus {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BusLocation]): BusLocation | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    active: boolean;
    routeId: [] | [string];
    message: string;
    timestamp: bigint;
    severity: _AlertSeverity;
}): {
    id: string;
    title: string;
    active: boolean;
    routeId?: string;
    message: string;
    timestamp: bigint;
    severity: AlertSeverity;
} {
    return {
        id: value.id,
        title: value.title,
        active: value.active,
        routeId: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.routeId)),
        message: value.message,
        timestamp: value.timestamp,
        severity: from_candid_AlertSeverity_n13(_uploadFile, _downloadFile, value.severity)
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bus: _Bus;
    location: _BusLocation;
}): {
    bus: Bus;
    location: BusLocation;
} {
    return {
        bus: from_candid_Bus_n19(_uploadFile, _downloadFile, value.bus),
        location: value.location
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _BusStatus;
    name: string;
    routeId: string;
    driverName: string;
}): {
    id: string;
    status: BusStatus;
    name: string;
    routeId: string;
    driverName: string;
} {
    return {
        id: value.id,
        status: from_candid_BusStatus_n21(_uploadFile, _downloadFile, value.status),
        name: value.name,
        routeId: value.routeId,
        driverName: value.driverName
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    warning: null;
} | {
    info: null;
} | {
    critical: null;
}): AlertSeverity {
    return "warning" in value ? AlertSeverity.warning : "info" in value ? AlertSeverity.info : "critical" in value ? AlertSeverity.critical : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    delayed: null;
} | {
    active: null;
} | {
    outOfService: null;
}): BusStatus {
    return "delayed" in value ? BusStatus.delayed : "active" in value ? BusStatus.active : "outOfService" in value ? BusStatus.outOfService : value;
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BusWithLocation>): Array<BusWithLocation> {
    return value.map((x)=>from_candid_BusWithLocation_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Bus>): Array<Bus> {
    return value.map((x)=>from_candid_Bus_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Alert>): Array<Alert> {
    return value.map((x)=>from_candid_Alert_n10(_uploadFile, _downloadFile, x));
}
function to_candid_AlertSeverity_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AlertSeverity): _AlertSeverity {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_Alert_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Alert): _Alert {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_BusStatus_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BusStatus): _BusStatus {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_Bus_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Bus): _Bus {
    return to_candid_record_n6(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    active: boolean;
    routeId?: string;
    message: string;
    timestamp: bigint;
    severity: AlertSeverity;
}): {
    id: string;
    title: string;
    active: boolean;
    routeId: [] | [string];
    message: string;
    timestamp: bigint;
    severity: _AlertSeverity;
} {
    return {
        id: value.id,
        title: value.title,
        active: value.active,
        routeId: value.routeId ? candid_some(value.routeId) : candid_none(),
        message: value.message,
        timestamp: value.timestamp,
        severity: to_candid_AlertSeverity_n3(_uploadFile, _downloadFile, value.severity)
    };
}
function to_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: BusStatus;
    name: string;
    routeId: string;
    driverName: string;
}): {
    id: string;
    status: _BusStatus;
    name: string;
    routeId: string;
    driverName: string;
} {
    return {
        id: value.id,
        status: to_candid_BusStatus_n7(_uploadFile, _downloadFile, value.status),
        name: value.name,
        routeId: value.routeId,
        driverName: value.driverName
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AlertSeverity): {
    warning: null;
} | {
    info: null;
} | {
    critical: null;
} {
    return value == AlertSeverity.warning ? {
        warning: null
    } : value == AlertSeverity.info ? {
        info: null
    } : value == AlertSeverity.critical ? {
        critical: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BusStatus): {
    delayed: null;
} | {
    active: null;
} | {
    outOfService: null;
} {
    return value == BusStatus.delayed ? {
        delayed: null
    } : value == BusStatus.active ? {
        active: null
    } : value == BusStatus.outOfService ? {
        outOfService: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
